config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'tasks#index'
  resources :tasks
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :labels

  namespace :admin do
      resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :tasks, through: :labelings

  validates :name, presence: true

end

app/models/labeling.rb
class Labeling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings

  validates :name, presence: true
  validates :content,presence: true
  validates :deadline,presence: true

  enum status: {waiting: 0,working: 1,completed: 2}
  enum priority: {low: 0,medium: 1,heigh: 2}

   scope :name_search, -> (name) {
     next if name.blank?
     where("name LIKE ?", "%#{name}%")
   }
   scope :status_search, -> (status) {
     next if status.blank?
     where(status: status)}

   scope :priority_search, -> (priority) {
     next if priority.blank?
     where(priority: priority)}

  scope :label_search, ->(label_ids){
    next if label_ids.blank?
    #ラベルがある時(false)
    joins(:labels).where(labels: { id: label_ids }).group(:id)}

  paginates_per 5
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  validates :password, presence: true, length: { minimum: 6 },on: :new
  has_secure_password
  # before_destroy :must_not_destroy_last_admin
  # before_destroy @user.admin < 1
  # after_destroy :must_not_destroy_last_admin
  private

  def must_not_destroy_last_admin
    throw(:abort)
    User.where(admin:true).count < 1
    # throw(:abort) if (tasks.user.admin < 1)
    # errors.add :base,"admin0人まで削除することができません"
  end

  def must_not_destroy_last_admin
    throw(:abort)
    User.where(admin:true).count < 1
    # throw(:abort) if (tasks.user.admin < 1)
    # errors.add :base,"admin0人まで削除することができません"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:edit,:show,:update,:destroy]
  before_action :authenticate_admin


  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # binding.pry
    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def show

  end

  def edit
  end

  def update
    if @user.update(user_params)
      # binding.pry
      redirect_to admin_users_path
      flash[:notice] = "ユーザを更新しました"
    else
      render :edit
    end
  end

  def destroy
    if current_user != @user
      @user.destroy
      redirect_to admin_users_path
      flash[:notice] = "ユーザーを削除しました"
    else
      redirect_to admin_users_path
      flash[:notice] = "ユーザーを削除できません"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmatin,:admin)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def authenticate_admin
    redirect_to root_url unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
    if current_user == nil
      redirect_to new_session_path
    end
  end

  add_flash_types :success, :info, :warning, :danger
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label,only: [:destroy]

  def index
    @labels = Label.all
  end

  def new
    @label = Label.new
  end

  def create
    @label = Label.new(label_params)
    if @label.save
      redirect_to labels_path,success:"ラベルを作成しました。"
    else
      render :new
    end
  end

  def destroy
    @label.destroy
    redirect_to labels_path,notice:"ラベルを削除しました。"
  end

  private

  def label_params
    params.require(:label).permit(:name)
  end

  def set_label
    @label = Label.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
     if user && user.authenticate(params[:session][:password])
       session[:user_id] = user.id
       redirect_to user_path(user.id)
     else
       flash.now[:danger] = 'ログインに失敗しました'
       render 'new'
     end
  end

  def destroy
    log_out
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  PER = 5
  before_action :set_task, only: [:show,:edit,:update,:destroy]
  before_action :authenticate_user
  def index
    @tasks = current_user.tasks.name_search(params.dig(:task, :name))
                          .status_search(params.dig(:task, :status))
                          .priority_search(params.dig(:task, :priority))
                          .label_search(params.dig(:task, :labels_ids))
                          .order(created_at: "DESC").page(params[:page]).per(PER)

      if  params[:sort_deadline]
          @tasks = current_user.tasks.order(deadline: "ASC").page(params[:page]).per(PER)
       elsif params[:sort_priority]
         @tasks = current_user.tasks.order(priority: "DESC").page(params[:page]).per(PER)
       end
    end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    if @task.save
      flash[:notice] = 'タスクの登録しました'
      redirect_to tasks_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      flash[:notice] = 'タスクの更新しました'
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    flash[:notice] = 'タスクの削除しました'
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name,:content,:deadline,:status,:priority, { label_ids: [] })
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_user, only: [:new]
  before_action :set_user, only:[:show]
  before_action :check_user,only:[:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # binding.pry
    if @user.save
      log_in @user
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
  end

  private

  def set_user
    @user = User.find(params[:id])
    # binding.pry
  end

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:admin)
  end

  def login_user
    if logged_in?
      redirect_to tasks_path
    end
  end

  def check_user
      if @user.id != current_user.id
        redirect_to tasks_path,notice:"権限がありません"
      end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def log_in(user)
   session[:user_id] = user.id
  end

  def log_out
   session.delete(:user_id)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1><%=t('view.edit_user') %></h1>

<%= link_to t('view.user_index'),admin_users_path %>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true,url:admin_user_path(@user.id),method: :patch ) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :admin %>
  <%= f.check_box :admin %>

  <%= f.submit "Edit account" %>
<% end %>

app/views/admin/users/index.html.erb
<h1><%= t('view.user_index') %></h1>

<p><%= notice %></p>

<table class="table table-bordered table-hover">
  <tr>
    <th><%= t('view.name') %></th>
    <th><%= t('view.email') %></th>
    <th><%= t('view.task_count') %></th>
    <th><%= t('view.check_admin') %></th>
    <th><%= t('view.details') %></th>
    <th><%= t('view.edit') %></th>
    <th><%= t('view.destroy') %></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <div classs="user">
      <td id="name"><%= user.name %></td>
      <td id="email"><%= user.email %></td>
      <td id="task_count"><%= user.tasks.count %></td>
      <td id="check_admin"><%= user.admin %></td>
      <td><%= link_to t('view.user_detail'), admin_user_path(user.id) %></td>
      <td><%= link_to t('view.user_edit'), edit_admin_user_path(user.id), data: { confirm: t('view.edit_task?') } %></td>
      <td><%= link_to t('view.user_destroy'), admin_user_path(user.id), method: :delete, data: { confirm: t('view.delete_task?') } %></td>
   </div>
  </tr>
<% end %>
</table>
<div class="create_user">
  <%= link_to t('view.create_user'),new_admin_user_path,class:"btn btn-info"%>
</div>

app/views/admin/users/new.html.erb
<h1><%= t('view.create_user')%></h1>

<%= link_to t('view.user_index'),admin_users_path %>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :admin_name %>

  <%= f.label :email %>
  <%= f.email_field :admin_email %>

  <%= f.label :password %>
  <%= f.password_field :admin_password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :admin_password_confirmation %>

  <%= f.label :admin %>
  <%= f.check_box :admin %>


  <%= f.submit "Create my account" %>
<% end %>

app/views/admin/users/show.html.erb
<h1><%= @user.name %><%= t('view.user_page') %></h1>

<p><%= t('view.email') %>: <%= @user.email %></p>

<p><%= t('view.admin') %>:<%= @user.admin %> </p>

<table class="table table-bordered table-hover">
  <tr>
    <th><%= t('view.name') %></th>
    <th><%= t('view.details') %></th>
    <th><%= t('view.deadline') %></th>
    <th><%= t('view.status') %></th>
    <th><%= t('view.priority') %></th>
  </tr>

<% @user.tasks.each do |task| %>
  <tr>
    <div classs="task">
      <td id="name"><%= task.name %></td>
      <td id="content"><%= task.content %></td>
      <td id="deadline"><%= task.deadline.strftime('%Y-%m-%d') %></td>
      <td id="status"><%= Task.statuses_i18n[task.status] %></td>
      <td id="priority"><%= Task.priorities_i18n[task.priority] %></td>
   </div>
  </tr>
<% end %>
</table>

<%= link_to t('view.back_user'), admin_users_path %>

<table class="table table-bordered table-hover">
  <tr>
    <th><%= t('view.name') %></th>
    <th><%= t('view.details') %></th>
    <th><%= t('view.deadline') %></th>
    <th><%= t('view.status') %></th>
    <th><%= t('view.priority') %></th>
  </tr>

<% @user.tasks.each do |task| %>
  <tr>
    <div classs="task">
      <td id="name"><%= task.name %></td>
      <td id="content"><%= task.content %></td>
      <td id="deadline"><%= task.deadline.strftime('%Y-%m-%d') %></td>
      <td id="status"><%= Task.statuses_i18n[task.status] %></td>
      <td id="priority"><%= Task.priorities_i18n[task.priority] %></td>
   </div>
  </tr>
<% end %>
</table>

app/views/labels/index.html.erb
<h2>ラベル一覧</h2>

  <table class="table table-bordered table-hover">
    <tr class="active">
      <th><%= t('view.label_name') %></th>
      <th><%= t('view.destroy') %></th>
    </tr>

    <% @labels.each do |label| %>
    <tr>
      <td><%= label.name %></td>
      <td><%= link_to t('view.destroy'), label_path(label.id), method: :delete ,data: { confirm: t('delete_task?') } %></td>
    </tr>
    <% end %>
  </table>

  <%= link_to t('view.new_task'), new_task_path, class:"btn btn-info" %>
  <%= link_to t('view.index'), tasks_path, class:"btn btn-info" %>
  <%= link_to t('view.label_create'), new_label_path, class:"btn btn-info" %>

app/views/labels/new.html.erb
<h1><%=t('view.label_create') %></h1>
<%= form_with(model: @label, local: true) do |form| %>
  <% if @label.errors.any? %>
    <div id="error_explanation">
      <h2><%= @label.errors.count %><%=t('view.have/errors') %></h2>
      <ul>

      <% @label.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="label_name">
    <%= form.label t('view.label_name') %>
    <%= form.text_field :name %>
  </div>
  <br>
  <%= form.submit %>
<% end %>
<br>
  <%= link_to t('view.new_task'), new_task_path, class:"btn btn-info" %>
  <%= link_to t('view.index'), tasks_path, class:"btn btn-info" %>
  <%= link_to t('view.label_index'), labels_path, class:"btn btn-info" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wanye</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>


  <body>
    <header>
      <div class="header">
        <nav>
          <ul class="top_menu clearfix">
              <% if logged_in? %>
            <li><%= link_to t('view.profile'), user_path(current_user.id) %></li>
            <li><%= link_to t('view.logout'), session_path(current_user.id), method: :delete %></li>
            <% if current_user.admin %>
            <li><%= link_to t('view.user_index'),admin_users_path %></li>
              <% end %>
                <% else %>
                <li><%= link_to t('view.signup'), new_user_path %></li>
                <li><%= link_to t('view.login'), new_session_path %></li>
              <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>

    <footer class="footer">
    <p>Copyright © 2019 Task Application Harinezumi.</p>
  </footer>





  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %> <%= t('view.have_error') %></h2>
      <ul>

      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="task_name">
    <%= form.label t('view.name') %>
    <%= form.text_field :name %>
  </div>
  <div class="task_content">
    <%= form.label t('view.details') %>
    <%= form.text_field :content %>
  </div>
  <div class="task_deadline">
    <%= form.label t('view.deadline') %>
    <%= form.date_field :deadline %>
  </div>
  <div class="task_status">
    <%= form.label t('view.status') %>
    <%= form.select :status, Task.statuses_i18n.invert, {include_blank: t('view.status')} %>
  </div>
  <div class="task_prioritys">
    <%= form.label t('view.priority') %>
    <%= form.select :priority, Task.priorities_i18n.invert, {include_blank: t('view.priority')} %>
  </div>
  <br>
  <% Label.all.each do |label| %>
    <%= form.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %>
    <label style="background-color: aquamarine"><%=label.name %></label>
  <% end %>
  <td>
  <%= form.submit class:"btn btn-info" %>
<% end %>
<p></p>
<%= link_to t('view.back_task'), tasks_path,class:"btn btn-info" %>

app/views/tasks/edit.html.erb
<h2><%=t('view.edit_task') %></h2>

 <%= render 'form' %>

app/views/tasks/index.html.erb
<h1><%= t('view.index') %></h1>

<p><%= notice %></p>

<%= form_with(model: Task.new,method: :get,local: true,url: tasks_path) do |form| %>
  <%= form.label :name_search, t('view.search_name') %>
  <%= form.text_field :name %>
  <%= form.label :status_search, t('view.select_status') %>
  <%= form.select :status, Task.statuses_i18n.invert, :include_blank => true %>

  <%= form.label :priority_search,t('view.select_priority') %>
  <%= form.select :priority, Task.priorities_i18n.invert,:include_blank => true %>
<br>
    <% Label.all.each do |label|%>
     <div class="label_search">
       <%= form.check_box :labels_ids, {multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false}, label[:id] %>
       <label class="form-check-label"><%= label.name %></label>
     </div>
    <% end %>

  <%= form.hidden_field :search, value: 'true' %>

  <%= form.submit t('view.search'),name:'search',class:"btn btn-info"%>
<% end %>

<div class="col-md-12">
<table class="table table-bordered table-hover">
  <tr>
    <th><%= t('view.name') %></th>
    <th><%= t('view.details') %></th>
    <th><%= t('view.deadline') %></th>
    <th><%= t('view.status') %></th>
    <th><%= t('view.priority') %></th>
    <th><%= t('view.details') %></th>
    <th><%= t('view.edit') %></th>
    <th><%= t('view.destroy') %></th>
    <th>ラベル</th>
  </tr>

<% @tasks.each do |task| %>
<!--  -->
  <tr>
    <div classs="task">
      <td id="name"><%= task.name %></td>
      <td id="content"><%= task.content %></td>
      <td id="deadline"><%= task.deadline.strftime('%Y-%m-%d') %></td>
      <td id="status"><%= Task.statuses_i18n[task.status] %></td>
      <td id="priority"><%= Task.priorities_i18n[task.priority] %></td>
   </div>
    <td><%= link_to t('view.check_details'), task_path(task.id) %></td>
    <td><%= link_to t('view.edit_task'), edit_task_path(task.id), data: { confirm: t('view.edit_task?') } %></td>
    <td><%= link_to t('view.delete_task'), task_path(task.id), method: :delete, data: { confirm: t('view.delete_task?') } %></td>
    <td>
    <% task.labels.each do |label| %>
      <%= label.name %>
    <% end %>
    </td>
  </tr>
<% end %>
</table>
</div>

 <%= paginate @tasks %>
<div class="link col-md-2">
<%= link_to t('view.new_post'),new_task_path,class:"btn btn-info" %>
</div>
<div class="link col-md-2">
<%= link_to t('view.sort_deadline'), tasks_path(sort_deadline: "true"),class:"btn btn-info",id:"sort_deadline01" %>
</div>
<div class="link col-md-2">
<%= link_to t('view.sort_priority'), tasks_path(sort_priority: "true"),class:"btn btn-info",id:"sort_deadline01" %>
</div>
<div class="link col-md-2">
<%= link_to t('view.back_sort'), tasks_path,class:"btn btn-info" %>
</div>
<div class="link col-md-2">
<%= link_to t('view.label_index'), labels_path,class:"btn btn-info" %>
</div>

app/views/tasks/new.html.erb
<h2><%= t('view.new_task') %></h2>

 <%= render 'form' %>

app/views/tasks/show.html.erb
<h1><%= t('view.task_details') %></h1>
<p><%= t('view.name') %>: <%= @task.name %></p>
<p><%= t('view.details') %>: <%= @task.content %></p>
<p><%= t('view.deadline') %>: <%= @task.deadline.strftime('%Y-%m-%d') %></p>
<p><%= t('view.status') %>: <%= Task.statuses_i18n[@task.status] %></p>
<p><%= t('view.priority') %>: <%= Task.priorities_i18n[@task.priority] %></p>

<p>
  <%= t('view.label_name') %>: <%@task.labels.each do |label| %>
  <%= label.name %>
  <% end %>
</p>


<%= link_to t('view.back_task'),tasks_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %><%= t('view.user_page') %></h1>

<p><%= t('view.email')%>: <%= @user.email %></p>

<%= link_to t('view.back_task'),tasks_path,class:"btn btn-info" %>